--[[
	This is the Paisley compiler.
	It takes Paisley code and compiles it into bytecode that is easy to interpret and run.
]]

require "stdlib"
require "json"

require "lex"
require "syntax"
require "closest_word"
require "fold_constants"
require "semantics"
require "codegen"

local expression = V1:gsub('\x0b', '\n')
local file = V2

--[[
	Command format is a string array, each element formatted as follows:
	"COMMAND_NAME:RETURN_TYPE"
	Where RETURN_TYPE is a Paisley data type, not a Lua type.

	Paisley types are one of the following:
		null
		boolean
		number
		string
		array
		any

	Note that this IS case-sensitive!
]]
ALLOWED_COMMANDS = V3
require "builtin_commands"

local lexer = Lexer(expression, file)
local t
local tokens = {}
for t in lexer do table.insert(tokens, t) end --Iterate to get tokens.

if COMPILER_DEBUG then
	function print_header(title)
		print('--------------------------')
		print(title)
		print('--------------------------')
	end
	print_header('Tokens')
	local i
	for i = 1, #tokens do
		print_token(tokens[i])
	end
end

local parser = SyntaxParser(tokens, file)
while parser.fold() do end --Iterate on the syntax tree. Follows iterator-like behavior.
if COMPILER_DEBUG then
	print_header('AST First Pass')
	print_tokens_recursive(parser.get()[1])
end

--Analyze the AST and check for any errors
local root = SemanticAnalyzer(parser.get(), file)
if COMPILER_DEBUG then
	print_header('After Semantic Analysis')
	print_tokens_recursive(root)
end

--Generate instruction representation
bytecode = generate_bytecode(root, file)
if COMPILER_DEBUG then
	print_header('Generated Bytecode')
	print_bytecode(bytecode)
end

output(json.stringify(bytecode), 1)
