return {
	--Operators
	['for'] = TOK.kwd_for,
	['if'] = TOK.kwd_if,
	['else'] = TOK.kwd_else,
	['+'] = TOK.op_plus,
	['-'] = TOK.op_minus,
	['*'] = TOK.op_times,
	['//'] = TOK.op_idiv,
	['/'] = TOK.op_div,
	['%'] = TOK.op_mod,
	['%%'] = TOK.op_divisible,
	['^'] = TOK.op_exponent,
	[':'] = TOK.op_slice,
	['&'] = TOK.op_count,
	['not'] = TOK.op_not,
	['and'] = TOK.op_and,
	['or'] = TOK.op_or,
	['xor'] = TOK.op_xor,
	['in'] = TOK.op_in,
	['exists'] = TOK.op_exists,
	['like'] = TOK.op_like,
	['=>'] = TOK.op_arrow,
	['>='] = TOK.op_ge,
	['>'] = TOK.op_gt,
	['<='] = TOK.op_le,
	['<'] = TOK.op_lt,
	['=='] = TOK.op_eq,
	['='] = TOK.op_eq,
	['~='] = TOK.op_ne,
	['!='] = TOK.op_ne,
	[','] = TOK.op_comma,
	['.'] = TOK.op_dot,
	['bitwise'] = TOK.op_bitwise,
}
