--Specify the number of parameters that each function must have
BUILTIN_FUNCS = {
	random_int = 2,
	random_float = 2,
	word_diff = 2,
	dist = 2,
	sin = 1,
	cos = 1,
	tan = 1,
	asin = 1,
	acos = 1,
	atan = 1,
	atan2 = 2,
	sqrt = 1,
	bytes = 2,
	sum = -1, --at least 1 param
	mult = -1,
	min = -1,
	max = -1,
	clamp = 3, --clamp(a, b, x) = min(b, max(a, x))
	smoothstep = 3,
	lerp = 3, --lerp(a, b, x) = a + x*(b - a) : 0 <= x <= 1
	split = 2,
	join = 2,
	type = 1,
	bool = 1,
	str = 1,
	num = 1,
	int = 1,
	floor = 1,
	ceil = 1,
	round = 1,
	abs = 1,
	append = 2,
	index = 2,
	lower = 1,
	upper = 1,
	camel = 1,
	replace = 3,
	json_encode = -2, --value of -N means that the function must have at least 1, and up to N, params.
	json_decode = 1,
	json_valid = 1,
	b64_encode = 1,
	b64_decode = 1,
	lpad = 3,
	rpad = 3,
	hex = 1,
	filter = 2,
	matches = 2,
	clocktime = 1,
	reverse = 1,
	sort = 1,
	reduce = 2,
	frombytes = 1,
	merge = 2,
	update = 3,
	insert = 3,
	delete = 2,
	random_element = 1,
	hash = 1,
	object = 1,
	array = 1,
	keys = 1,
	values = 1,
	pairs = 1,
	interleave = 2,
	unique = 1,
	union = 2,
	intersection = 2,
	difference = 2,
	symmetric_difference = 2,
	is_disjoint = 2,
	is_subset = 2,
	is_superset = 2,
	count = 2,
	find = 3,
	flatten = 1,
	sinh = 1,
	cosh = 1,
	tanh = 1,
	sign = 1,
	ascii = 1,
	char = 1,
	beginswith = 2,
	endswith = 2,
	to_base = 3,
	time = 1,
	date = 1,
	random_elements = 2,
	shuffle = 1,
	match = 2,
	splice = 4,
	uuid = 0,
	glob = -1,
	xml_encode = 1,
	xml_decode = 1,
	log = -2,
	normalize = 1,
	random_weighted = 2,
	trim = -2,
	modf = 1,
	all = 1,
	any = 1,
	cot = 1,
	acot = 1,
	sec = 1,
	asec = 1,
	csc = 1,
	acsc = 1,
	from_base = 2,
	chunk = 2,
	--[[minify-delete]]
	toepoch = 1,
	fromepoch = 1,
	epochnow = 0,
	file_glob = 1,
	file_exists = 1,
	file_size = 1,
	file_read = 1,
	file_write = 2,
	file_append = 2,
	file_delete = 1,
	dir_create = -2,
	dir_list = 1,
	dir_delete = -2,
	file_type = 1,
	file_stat = 1,
	file_copy = 2,
	file_move = 2,
	--[[/minify-delete]]
}

--[[minify-delete]]
function FUNC_SANDBOX_RESTRICT()
	BUILTIN_FUNCS['file_glob'] = nil
	SANDBOX = true
end

if _G['RESTRICT_TO_PLASMA_BUILD'] or _G['SANDBOX'] then
	FUNC_SANDBOX_RESTRICT()
end
--[[/minify-delete]]
