return {
	{ description = "The input file, or `-` to read from stdin",                     name = "input",             type = "string" },
	{ description = "Prints help information",                                       long = "help",              short = "h" },
	{ description = "Prints version information",                                    long = "version",           short = "V" },
	{ description = "The next parameter is the output file (use `-` for stdout)",    long = "output",            short = "o",     type = "string" },
	{ description = "Start the Paisley runtime as an interactive REPL",              long = "repl",              short = "r" },
	{ description = "Output bytecode instead of running the script",                 long = "bytecode",          short = "b" },
	{ description = "Pretty-print bytecode output",                                  long = "pretty",            short = "p" },
	{ description = "Pretend that stdin input has the given filename",               long = "stdin",             type = "string", arg = "[FILE]" },
	{ description = "Don't report errors in the syntax tree",                        long = "no-ast-errors" },
	{ description = "Don't remove 'dead code' that will never get run",              long = "no-prune-dead-code" },
	{ description = "Don't allow `and` and `or` expressions to short-circuit",       long = "no-short-circuit" },
	{ description = "Allow any functions to be redefined without error",             long = "allow-elision" },
	{ description = "Print all generated tokens and then exit",                      long = "tokens" },
	{ description = "Print the abstract syntax tree and then exit",                  long = "ast" },
	{ description = "Print the AST after semantic analysis and then exit",           long = "ast-sem" },
	{ description = "Restrict to only features available in the Plasma build",       long = "plasma" },
	{ description = "Generate runtime or compiler text for the Plasma build",        long = "plasma-build",      type = "string", arg = "[TYPE]",              options = { "compiler", "runtime" } },
	{ description = "Print introspective data about the Paisley language",           long = "introspect" },
	{ description = "If introspecting, list all functions",                          long = "functions" },
	{ description = "If introspecting functions, show or exclude synonym functions", long = "synonyms",          type = "string", options = { "only", "none" } },
	{ description = "If introspecting, list all commands",                           long = "commands" },
	{ description = "Define an existing command on the target device",               short = "c",                type = "array",  name = "external_cmds",      composite = true,                   arg = "[CMD]" },
	{ description = "If introspecting, output details about the function",           short = "if",               type = "array",  name = "introspect_func",    composite = true,                   arg = "[FUNC_NAME]" },
	{ description = "If introspecting, output details about the command",            short = "ic",               type = "array",  name = "introspect_cmds",    composite = true,                   arg = "[CMD_NAME]" },
	{ description = "Output a standalone binary (or source code if no output file)", long = "standalone",        short = "s" },
	{ description = "Precompile C++ runtime object files",                           long = "cpp-precompile" },
	{ description = "Remove precompiled C++ object files",                           long = "cpp-clean" },
	{ description = "Compress bytecode or standalone output with zlib compression",  long = "compress",          short = "z" },
	{ description = "Choose a specific language to compile the standalone binary",   long = "target",            type = "string", arg = "[TARGET]",            options = { "lua", "c", "cpp" } },
	{ description = "Allow unrecognized commands to coerce to shell exec",           long = "shell",             short = "l" },
	{ description = "Disable features/cmds that could affect the system (e.g. `?`)", long = "sandbox" },
	{ description = "List the recommended Lua packages to be installed",             long = "rocks" },
	{ description = "Disable usage of auxilliary Lua libraries",                     long = "no-rocks" },
	{ description = "Validate the program, but don't run it",                        long = "dry-run" },
	{ description = "Output detailed info in an easy-to-parse format",               long = "language-server" },
	{ description = "Format the given program input, then exit",                     long = "format" },
	{ description = "If formatting, set the indent to the given string",             long = "indent",            type = "string", arg = "[INDENT]",            default = "\t" },
	{ description = "Treat any warnings as errors",                                  long = "werror" },
	--[[no-install]]
	{ description = "Compile the Paisley application into a standalone executable",  long = "install" },
	{ description = "Compile the main executable with the given compiler",           long = "compile-self",      type = "string", arg = "[COMPILER]" },
	{ description = "Bundle the main executable into a single Lua file and exit",    long = "bundle-self" },
	--[[/no-install]]
}
